media:
  - input: "public/images/projects"
    output: "/images/projects"

content:
  - name: "projects"
    label: "Projects"
    type: "collection"
    path: "src/content/projects"
    fields:
      - { name: "title", label: "Project Title", type: "string", required: true }
      - { name: "image", label: "Main Image", type: "image", required: true }
      - { name: "description", label: "Short Description", type: "string", required: true }
      - { name: "projectType", label: "Project Type", type: "string", default: "Personal Project" }
      - name: "tags"
        label: "Technologies Used (Stack)"
        type: "string"
        list: true

      - { name: "link_github", label: "GitHub Link", type: "string" }
      - { name: "link_preview", label: "Preview Link", type: "string" }
      - { name: "projectPurposeAndGoal", label: "Project Purpose and Goal", type: "rich-text" }
      - name: "webStackAndExplanation"
        label: "Web Stack & Explanation"
        type: "object"
        list: true
        fields:
          - { name: "stackName", label: "Stack Name", type: "string" }
          - { name: "explanation", label: "Explanation", type: "string" }
          - { name: "icon", label: "Stack Icon", type: "image" }
      - name: "projectImages"
        label: "Project Images (Grid of 4)"
        type: "image"
        list: true
      - { name: "problemAndThoughts", label: "Problem and Thoughts", type: "rich-text" }
      - { name: "problemImage", label: "Problem Image", type: "image" }
      - { name: "lessonsLearned", label: "Lessons Learned", type: "rich-text" }
      - { name: "body", label: "Full Details (Markdown Body)", type: "rich-text" }

    - name: "pages"
    label: "Pages Content"
    type: "files" # هنا نستخدم "files" بدلاً من "collection"
    files:
      # 1. إدارة محتوى الصفحة الرئيسية
      - name: "home"
        label: "Home Page"
        file: "src/content/singletons/home.md"
        fields:
          - { name: "headline", label: "Headline", type: "rich-text" }

      # 2. إدارة محتوى صفحة "عني"
      - name: "about"
        label: "About Page"
        file: "src/content/singletons/about.md"
        fields:
          - { name: "title", label: "Page Title", type: "string" }
          - { name: "body", label: "Page Content", type: "rich-text" }

      # 3. إدارة محتوى قسم الخبرات
      - name: "experience"
        label: "Experience Section"
        file: "src/content/singletons/experience.md"
        fields:
          - name: "cv_link"
            label: "CV Download Link"
            type: "string"
          - name: "experiences"
            label: "Experience Entries"
            type: "object"
            list: true
            fields:
              - { name: "years", label: "Years", type: "string" }
              - { name: "title", label: "Job Title", type: "string" }
              - { name: "description", label: "Description", type: "rich-text" }